### ISSUE TITLE
Update dockerlint

### ISSUE THREAD

**Issue by Pluckerpluck** [AtomLinter/linter-docker#25]
Can this be upgraded to the newer version of dockerlint?

Specifically because of a bug fixed:

https://github.com/RedCoolBeans/dockerlint/issues/3

**Comment by Arcanemagus** [comment]
@johnwebbcole Are you still maintaining this? #18 has been sitting around for a while which should fix this. Since #10 hasn't been dealt with yet I have no idea if that's safe to merge though...

**Comment by johnwebbcole** [comment]
Both should be safe to merge.  I can get it later tonight.

**Comment by johnwebbcole** [comment]
Updated, but I'm getting an error...

**Comment by Arcanemagus** [comment]
Let me know if you need help with anything 😉.

**Comment by Arcanemagus** [comment]
Marking this as closed as there are reports that it is currently working.
