### ISSUE TITLE
Get error on save in Dockerfile

### ISSUE THREAD

**Issue by cap10morgan** [AtomLinter/linter-docker#29]
Every time I save a (valid) Dockerfile with this enabled, I get the following error message:

<img width="451" alt="screen shot 2016-11-29 at 7 30 59 am" src="https://cloud.githubusercontent.com/assets/59748/20709915/ea0a916c-b605-11e6-8b9a-4c8e9de24ccf.png">

This is on macOS Sierra 10.12.1 in Atom 1.12.6 with dockerlint 0.2.0 installed globally via `npm` (the error happens both when I point linter-docker at this executable and when I leave it on the default). I have version 1.11.21 of the `linter` plugin installed.

**Comment by johnzook** [comment]
Submitted pull request #30, which fixes the issue for me. For those with the issue, as a temporary stop-gap you can check out the repository locally, follow the [Development Instructions](https://github.com/AtomLinter/linter-docker#development-and-testing), and make the change to a local install of linter-docker.

FYI @Arcanemagus, you look to be the most recent contributor able to review and get this merged with a new release.

Thank you!
