### ISSUE TITLE
Some messages are not displayed

### ISSUE THREAD

**Issue by lucasdf** [AtomLinter/linter-docker#37]
The current regex message parser does not include all kind of messages returned by dockerlint.

Empty file unparsed error: `ERROR: /path/to/Dockerfile does not contain any instructions`

Example 2:
```
RUN apt-get update
```
Unparsed error: `ERROR: First instruction must be 'FROM', is: RUN`

Example 3:
```
FROM someimage
CMD ["ls"]
CMD ["ls"]
```
Unparsed error: `ERROR: Multiple CMD instructions found, only line 3 will take effect`

**Comment by Arcanemagus** [comment]
Looks like this is still using the ancient `parse()` function with a regex that doesn't seem to capture everything.

**Comment by johnwebbcole** [comment]
Yeah, it's 2 years old, I wonder how hard it would be to update with he standard v2 js example...  I'll work on that this weekend.

**Comment by lucasdf** [comment]
Hi John,
I am actually just finishing a PR that fixes this.


On Aug 26, 2017 11:11 AM, "John Cole" <notifications@github.com> wrote:

Yeah, it's 2 years old, I wonder how hard it would be to update with he
standard v2 js example... I'll work on that this weekend.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AtomLinter/linter-docker/issues/37#issuecomment-325131213>,
or mute the thread

**Comment by johnwebbcole** [comment]
@lucasdf Great!
