### ISSUE TITLE
Alternative to dockerlint compatibility?

### ISSUE THREAD

**Issue by exuperok** [AtomLinter/linter-docker#48]
Hello, I have noticed that dockerlint doesn't catch many issues in dockefile, such as the fact that base image name doesn't"t have a version or the maintainer is still used instead of using label etc... Is it possible to use lintter-docker with an alternative dockerfile linter npm package that I have used to great effects in my  ci pipeline to better catch errors.

**Comment by lucasdf** [comment]
AFAIK there is no generic linter that you could just point it to another linter. 

For Docker, you may want to check [linter-hadolint](https://github.com/AtomLinter/linter-hadolint). It has a broader scope and it has more checks when compared to linter-docker. You must have [hadolint](https://github.com/hadolint/hadolint) installed to use it.

What is the name of this alternative dockerfile linter that you have been using?

**Comment by lucasdf** [comment]
Closing... Feel free to open a new issue if you have more questions.
