### ISSUE TITLE
should not require WORKDIR to be absolute path

### ISSUE THREAD

**Issue by sedwards28** [AtomLinter/linter-docker#55]
The linter complains about WORKDIR calls that do not include absolute paths.
```
WORKDIR /
WORKDIR go
```
The linter complains about the second line above, however, the dockerfile reference documentation clearly states that WORKDIR calls with relative paths will result in the path relative to the previous WORKDIR calls.
https://docs.docker.com/engine/reference/builder/#workdir

In other words, this should be allowed. Why does the linter complain?

**Comment by lucasdf** [comment]
Hi @sedwards28,

The linter-docker plugin works as a wrapper around [dockerlint](https://github.com/RedCoolBeans/dockerlint). 

I would recommend you to open a new issue in the dockerlint repository so they may check and fix it.

**Comment by sedwards28** [comment]
Sounds good. I've created an issue in the dockerlint repo
https://github.com/RedCoolBeans/dockerlint/issues/53
