### ISSUE TITLE
[Request|Query] Can it support dockerfilelint

### ISSUE THREAD

**Issue by jonyeezs** [AtomLinter/linter-docker#60]
This [linter](https://github.com/replicatedhq/dockerfilelint) is awesome. It has an extensive static analytical abilities.

Would this linter be able to use that as its executable?

**Comment by Arcanemagus** [comment]
If it has the _exact_ same output format it would, however it's likely better to create a new provider to handle that.

Feel free to reach out on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) if you were going to take that on and need any help!
